-- 扩大短字段长度，防止数据截断错误
ALTER TABLE `samples`
    MODIFY COLUMN `qq` VARCHAR(50) DEFAULT NULL COMMENT 'QQ',
    MODIFY COLUMN `mobile` VARCHAR(30) DEFAULT NULL COMMENT '手机',
    MODIFY COLUMN `contact_phone` VARCHAR(30) DEFAULT NULL COMMENT '联系电话',
    MODIFY COLUMN `fax` VARCHAR(30) DEFAULT NULL COMMENT '传真',
    MODIFY COLUMN `sample_unit` VARCHAR(50) DEFAULT NULL COMMENT '样品单位',
    MODIFY COLUMN `packing_unit` VARCHAR(50) DEFAULT NULL COMMENT '装箱单位',
    MODIFY COLUMN `booth_no` VARCHAR(100) DEFAULT NULL COMMENT '摊位号';
