spring:
  devtools:
    restart:
      enabled: false
  web:
    resources:
      static-locations: classpath:/static/

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl

app:
  upload:
    path: d:/客户端测试/photo-management/uploads
    image-path: d:/客户端测试/photo-management/images
    thumbnail-path: d:/客户端测试/photo-management/thumbnails
    video-path: d:/客户端测试/photo-management/videos
    ffmpeg-path: ffmpeg

search:
  image:
    engine: deep
    siamese-model-path:

pgvector:
  enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/photo_management
    username: postgres
    password: 123456
